from __future__ import annotations

import json
from pathlib import Path

from .models import (
    AgentInstance,
    AgentRoleSpec,
    AgentSkillSpec,
    AppSettings,
    ApprovalCreateRequest,
    ApprovalRequest,
    BoardBriefing,
    ChairmanInboxItem,
    ClientRecord,
    CompanyDNA,
    CompletionContract,
    DecisionRecord,
    DelegationRecord,
    DocumentRecord,
    DocumentVersion,
    EscalationRecord,
    FileAssetRecord,
    FileMoveRecord,
    GitChangeRecord,
    GovernanceReview,
    KnowledgeSnapshot,
    KnowledgeUpdate,
    MemoryPromotionReview,
    MatterDecisionRecord,
    MatterRecord,
    MeetingRecord,
    MissionDefinition,
    MissionTeam,
    OnboardingAnswers,
    OnboardingPreview,
    OpenQuestionRecord,
    OrganizationSnapshot,
    PlannerAction,
    PlannerPlan,
    PraetorBriefing,
    PromotionFinding,
    ReviewPolicy,
    RunAttempt,
    RunRecord,
    RoleDefinition,
    SkillSource,
    StandingOrder,
    TaskDefinition,
    WorkflowContract,
    WorkspaceRestructurePlan,
    WorkspaceScope,
    WorkspaceReconciliationIssue,
    WorkspaceReconciliationReport,
    WorkspaceStewardSnapshot,
    WorkSession,
    WorkSessionTurn,
)


SCHEMA_MODELS = {
    "app_settings": AppSettings,
    "company_dna": CompanyDNA,
    "agent_role_spec": AgentRoleSpec,
    "skill_source": SkillSource,
    "agent_skill_spec": AgentSkillSpec,
    "agent_instance": AgentInstance,
    "mission_team": MissionTeam,
    "delegation_record": DelegationRecord,
    "board_briefing": BoardBriefing,
    "escalation_record": EscalationRecord,
    "standing_order": StandingOrder,
    "completion_contract": CompletionContract,
    "organization_snapshot": OrganizationSnapshot,
    "role_definition": RoleDefinition,
    "mission_definition": MissionDefinition,
    "task_definition": TaskDefinition,
    "decision_record": DecisionRecord,
    "approval_request": ApprovalRequest,
    "approval_create_request": ApprovalCreateRequest,
    "chairman_inbox_item": ChairmanInboxItem,
    "meeting_record": MeetingRecord,
    "onboarding_answers": OnboardingAnswers,
    "onboarding_preview": OnboardingPreview,
    "planner_action": PlannerAction,
    "planner_plan": PlannerPlan,
    "praetor_briefing": PraetorBriefing,
    "run_attempt": RunAttempt,
    "run_record": RunRecord,
    "workflow_contract": WorkflowContract,
    "workspace_scope": WorkspaceScope,
    "work_session": WorkSession,
    "work_session_turn": WorkSessionTurn,
    "client_record": ClientRecord,
    "matter_record": MatterRecord,
    "document_record": DocumentRecord,
    "document_version": DocumentVersion,
    "file_asset_record": FileAssetRecord,
    "file_move_record": FileMoveRecord,
    "git_change_record": GitChangeRecord,
    "workspace_reconciliation_issue": WorkspaceReconciliationIssue,
    "workspace_reconciliation_report": WorkspaceReconciliationReport,
    "workspace_restructure_plan": WorkspaceRestructurePlan,
    "workspace_steward_snapshot": WorkspaceStewardSnapshot,
    "matter_decision_record": MatterDecisionRecord,
    "open_question_record": OpenQuestionRecord,
    "knowledge_update": KnowledgeUpdate,
    "knowledge_snapshot": KnowledgeSnapshot,
    "memory_promotion_review": MemoryPromotionReview,
    "promotion_finding": PromotionFinding,
    "governance_review": GovernanceReview,
    "review_policy": ReviewPolicy,
}


def export_json_schemas(output_dir: Path) -> list[Path]:
    output_dir.mkdir(parents=True, exist_ok=True)
    generated: list[Path] = []
    for name, model in SCHEMA_MODELS.items():
        path = output_dir / f"{name}.schema.json"
        path.write_text(
            json.dumps(model.model_json_schema(), indent=2, ensure_ascii=True),
            encoding="utf-8",
        )
        generated.append(path)
    return generated
