import json
import re
from http.server import BaseHTTPRequestHandler, HTTPServer


OUTPUT_RE = re.compile(r"- (/workspace/[^\s]+)")


class Handler(BaseHTTPRequestHandler):
    def do_GET(self):
        body = b'{"ok": true}'
        self.send_response(200)
        self.send_header("Content-Type", "application/json")
        self.send_header("Content-Length", str(len(body)))
        self.end_headers()
        self.wfile.write(body)

    def do_POST(self):
        length = int(self.headers.get("Content-Length", "0"))
        raw = self.rfile.read(length).decode("utf-8")
        payload = json.loads(raw)
        messages = payload.get("messages") or []
        prompt = messages[-1].get("content", "") if messages else ""
        if "Praetor CEO planner" in prompt:
            planner_payload = {
                "intent": "mission_draft",
                "response": "Planner created a mission draft, memory update, and decision checkpoint.",
                "actions": [
                    {
                        "type": "mission_draft",
                        "title": "LLM planner smoke mission",
                        "body": "Validate that the LLM planner can return structured actions.",
                        "metadata": {"domains": ["operations"], "priority": "high", "requested_outputs": []},
                    },
                    {
                        "type": "memory_update",
                        "title": "Planner memory",
                        "body": "LLM planner smoke memory.",
                        "metadata": {"page": "CEO Memory.md"},
                    },
                ],
            }
            body = {
                "id": "chatcmpl_fake_planner",
                "object": "chat.completion",
                "choices": [
                    {
                        "index": 0,
                        "message": {"role": "assistant", "content": json.dumps(planner_payload)},
                        "finish_reason": "stop",
                    }
                ],
                "usage": {"prompt_tokens": 123, "completion_tokens": 45},
            }
            encoded = json.dumps(body).encode("utf-8")
            self.send_response(200)
            self.send_header("Content-Type", "application/json")
            self.send_header("Content-Length", str(len(encoded)))
            self.end_headers()
            self.wfile.write(encoded)
            return
        match = OUTPUT_RE.search(prompt)
        output_path = match.group(1) if match else "/workspace/Projects/Fake/PROJECT.md"
        body = {
            "id": "chatcmpl_fake",
            "object": "chat.completion",
            "choices": [
                {
                    "index": 0,
                    "message": {
                        "role": "assistant",
                        "content": json.dumps(
                            {
                                "summary": "API mode generated the requested file.",
                                "files": [
                                    {
                                        "path": output_path,
                                        "content": "# Generated by API Mode\n\nThis file was produced by the fake OpenAI server.\n",
                                    }
                                ],
                                "decisions": ["Validated API mode output path."],
                                "notes": ["Fake server response."],
                            }
                        ),
                    },
                    "finish_reason": "stop",
                }
            ],
            "usage": {"prompt_tokens": 321, "completion_tokens": 87},
        }
        encoded = json.dumps(body).encode("utf-8")
        self.send_response(200)
        self.send_header("Content-Type", "application/json")
        self.send_header("Content-Length", str(len(encoded)))
        self.end_headers()
        self.wfile.write(encoded)

    def log_message(self, *_args):
        return


def main() -> int:
    server = HTTPServer(("127.0.0.1", 9760), Handler)
    try:
        server.serve_forever()
    except KeyboardInterrupt:
        pass
    finally:
        server.server_close()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
